baseURL = "https://kwappa.github.io/"
languageCode = "ja"
title = "kwappa on the net"
publishDir = "docs"
theme = "hyde"
hasCJKLanguage = true

[menu]
  main = [
    { name = "Logs", url = "/logs" },
    { name = "Tweets", url = "https://kwappa.github.io/tweets" },
  ]


[params]
  themeColor = "theme-base-0d"
  copyright  = "SHIOYA, Hiromu"
  description = """
  
"""
  googleAnalytics = "UA-107867268-1"
