baseURL = "https://kwappa.github.io/"
languageCode = "ja"
title = "kwappa on the net"
publishDir = "docs"
theme = "hyde"

[params]
  themeColor = "theme-base-0d"
  copyright  = "SHIOYA, Hiromu"
  description = """
  
"""
  googleAnalytics = "UA-107867268-1"
